### ISSUE TITLE
HMAC security useless because of debug output

### ISSUE THREAD

**Issue by keeshoekzema** [RX14/camo.cr#8]
The hmac security in this camo implementation is fine. Except you print out the expected key in case it doesn't match. That means it's trivial to generate urls.

Do not output the expected checksum in request.cr:23 it makes the entire hmac-security useless.

**Comment by RX14** [comment]
Absolutely my bad, I'll remove it straight away.

**Comment by RX14** [comment]
Thanks for the report!
