### ISSUE TITLE
It has build problems on crystal 1.0.0

### ISSUE THREAD

**Issue by tclaus** [RX14/camo.cr#9]
Tried to install / setup on a Crystal 1.0.0 box, 
After cloning git and ' shards install' it spills out an error. 

<img width="490" alt="Bildschirmfoto 2021-05-18 um 18 53 41" src="https://user-images.githubusercontent.com/501326/118692450-61819c80-b80a-11eb-8ae7-2e1e65c5ffc4.png">

**Comment by RX14** [comment]
Should be fixed now

**Comment by tclaus** [comment]
Wow - that was fast. 
I installed it in the meantime on my service.. Up and running! 
Thanks you your fast response. Everything seems to work.
